name: Build Fedecat Shooting EXE

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build EXE with PyInstaller and icon
        run: |
          pyinstaller --noconfirm --onefile --windowed --name "FedecatShooting" ^
            --icon "icono_fedecat.ico" ^
            --add-data "Tiradores_v4.xlsx;." ^
            --add-data "Resultados.xlsx;." ^
            --hidden-import=kivy.deps.sdl2 ^
            --hidden-import=kivy.deps.glew ^
            --hidden-import=kivymd.toast ^
            FedecatShooting.py

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: FedecatShooting_exe
          path: dist/FedecatShooting.exe
